import { useState } from 'react';
import axios from 'axios';
import Navbar from '../components/Navbar';

const Diet = () => {
  const [formData, setFormData] = useState({ age: '', gender: '', goal: '', specifications: '' });
  const [dietPlan, setDietPlan] = useState('');
  const [loading, setLoading] = useState(false);

  const handleGenerate = async (e) => {
    e.preventDefault();
    setLoading(true);
    setDietPlan(''); // Clear old plan

    try {
      // Calling our newly fixed backend!
      const res = await axios.post('http://localhost:5000/api/diet/generate', formData);
      setDietPlan(res.data.dietPlan);
    } catch (err) {
      alert("Error generating plan: " + (err.response?.data?.message || err.message));
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar />
      <main className="max-w-4xl mx-auto py-10 px-4">
        
        <header className="mb-10 text-center">
          <h2 className="text-3xl font-extrabold text-gray-900 tracking-tight">AI Nutritionist</h2>
          <p className="text-gray-500 mt-2">Get a custom meal plan generated by Growone AI.</p>
        </header>

        <div className="bg-white rounded-3xl shadow-sm border border-gray-100 p-8 mb-8">
          <form onSubmit={handleGenerate} className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="text-xs font-bold text-gray-400 uppercase ml-1">Age</label>
                <input type="number" required className="w-full mt-1 p-4 bg-gray-50 rounded-2xl outline-none focus:ring-2 focus:ring-blue-500" onChange={(e) => setFormData({...formData, age: e.target.value})} />
              </div>
              <div>
                <label className="text-xs font-bold text-gray-400 uppercase ml-1">Gender</label>
                <select required className="w-full mt-1 p-4 bg-gray-50 rounded-2xl outline-none focus:ring-2 focus:ring-blue-500" onChange={(e) => setFormData({...formData, gender: e.target.value})}>
                  <option value="">Select</option>
                  <option value="Male">Male</option>
                  <option value="Female">Female</option>
                </select>
              </div>
            </div>

            <div>
              <label className="text-xs font-bold text-gray-400 uppercase ml-1">Fitness Goal</label>
              <select required className="w-full mt-1 p-4 bg-gray-50 rounded-2xl outline-none focus:ring-2 focus:ring-blue-500" onChange={(e) => setFormData({...formData, goal: e.target.value})}>
                <option value="">Select your goal</option>
                <option value="Weight Loss">Weight Loss</option>
                <option value="Muscle Gain">Muscle Gain</option>
                <option value="Maintain Weight">Maintain Weight</option>
              </select>
            </div>

            <div>
              <label className="text-xs font-bold text-gray-400 uppercase ml-1">Any Preferences? (Optional)</label>
              <input type="text" placeholder="e.g., Vegetarian, High Protein, Cheap ingredients" className="w-full mt-1 p-4 bg-gray-50 rounded-2xl outline-none focus:ring-2 focus:ring-blue-500" onChange={(e) => setFormData({...formData, specifications: e.target.value})} />
            </div>

            <button type="submit" disabled={loading} className="w-full bg-blue-600 text-white p-4 rounded-2xl font-bold hover:bg-blue-700 transition shadow-lg disabled:opacity-50">
              {loading ? "Generating Plan..." : "Generate Diet Plan"}
            </button>
          </form>
        </div>

        {/* AI Output Box */}
        {dietPlan && (
          <div className="bg-gradient-to-br from-gray-900 to-blue-900 text-white rounded-3xl p-8 shadow-2xl">
            <h3 className="text-xl font-bold mb-6 text-blue-300">Your Custom Growone Plan:</h3>
            <div className="prose prose-invert max-w-none whitespace-pre-wrap">
              {dietPlan}
            </div>
          </div>
        )}

      </main>
    </div>
  );
};

export default Diet; // <--- THIS IS THE LINE THAT WAS MISSING!